In [1]:
import pandas as pd
import numpy as np

In [2]:
df_orders = pd.read_csv("order_reviews.csv")
df_orders[df_orders["review_score"]==1]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
5,15197aa66ff4d0650b5434f1b46cda19,b18dcdf73be66366873cd26c5724d1dc,1,NaN,NaN,2018-04-13 00:00:00,2018-04-16 00:39:37
19,373cbeecea8286a2b66c97b1b157ec46,583174fbe37d3d5f0d6661be3aad1786,1,Não chegou meu produto,Péssimo,2018-08-15 00:00:00,2018-08-15 04:10:37
29,2c5e27fc178bde7ac173c9c62c31b070,0ce9a24111d850192a933fcaab6fbad3,1,NaN,Não gostei ! Comprei gato por lebre,2017-12-13 00:00:00,2017-12-16 07:14:07
32,58044bca115705a48fe0e00a21390c54,68e55ca79d04a79f20d4bfc0146f4b66,1,NaN,Sempre compro pela Internet e a entrega ocorre...,2018-04-08 00:00:00,2018-04-09 12:22:39
39,9fd59cd04b42f600df9f25e54082a8d1,3c314f50bc654f3c4e317b055681dff9,1,NaN,Nada de chegar o meu pedido.,2017-04-21 00:00:00,2017-04-23 05:37:03
...,...,...,...,...,...,...,...
99930,2fc8295a24978092328d3a329d22940e,e809c167a9cfd31aee1293abe8995065,1,NaN,Eu recebi o seguinte email e preciso saber com...,2018-02-09 00:00:00,2018-02-13 13:03:24
99944,3450ec3bbabeb09a08b00fc72da87a30,c46f950813dd2dd9bab4188dceb83175,1,NaN,Boa tarde. \r\nNão recebo todos os produtos fa...,2017-12-08 00:00:00,2017-12-08 19:07:00
99959,6cf47345d15e054dd6df872e929bdb27,54e6829fe81bc86cf88b12e6d07ea298,1,NaN,NaN,2017-06-08 00:00:00,2017-06-08 22:52:39
99998,be360f18f5df1e0541061c87021e6d93,f8bd3f2000c28c5342fedeb5e50f2e75,1,NaN,Solicitei a compra de uma capa de retrovisor c...,2017-12-15 00:00:00,2017-12-16 01:29:43
99999,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [3]:
df_orders.index

RangeIndex(start=0, stop=100000, step=1)

In [5]:
df_semantic = pd.read_csv("polarity.csv")
df_semantic

,Unnamed: 0,Unnamed: 0.1,review_score,review_comment_message,review_model_score,polarity
0,0,3.0,5.0,Recebi bem antes do prazo estipulado.,0.572372,neutral
1,1,4.0,5.0,Parabéns lojas lannister adorei comprar pela I...,0.993573,positive
2,2,9.0,4.0,aparelho eficiente. no site a marca do aparelh...,0.959237,positive
3,3,12.0,4.0,"Mas um pouco ,travando...pelo valor ta Boa.\r\n",0.816860,positive
4,4,15.0,5.0,"Vendedor confiável, produto ok e entrega antes...",0.936436,positive
...,...,...,...,...,...,...
41750,41750,99983.0,5.0,Entregou dentro do prazo. O produto chegou em ...,0.984779,positive
41751,41751,99990.0,3.0,"O produto não foi enviado com NF, não existe v...",0.939961,positive
41752,41752,99996.0,5.0,"Excelente mochila, entrega super rápida. Super...",0.984625,positive
41753,41753,99998.0,1.0,Solicitei a compra de uma capa de retrovisor c...,0.337860,negative
41754,41754,99999.0,1.0,"meu produto chegou e ja tenho que devolver, po...",0.240128,negative

In [6]:
df_semantic.rename(columns={'Unnamed: 0.1': 'indx'}, inplace=True)
df_semantic

,Unnamed: 0,indx,review_score,review_comment_message,review_model_score,polarity
0,0,3.0,5.0,Recebi bem antes do prazo estipulado.,0.572372,neutral
1,1,4.0,5.0,Parabéns lojas lannister adorei comprar pela I...,0.993573,positive
2,2,9.0,4.0,aparelho eficiente. no site a marca do aparelh...,0.959237,positive
3,3,12.0,4.0,"Mas um pouco ,travando...pelo valor ta Boa.\r\n",0.816860,positive
4,4,15.0,5.0,"Vendedor confiável, produto ok e entrega antes...",0.936436,positive
...,...,...,...,...,...,...
41750,41750,99983.0,5.0,Entregou dentro do prazo. O produto chegou em ...,0.984779,positive
41751,41751,99990.0,3.0,"O produto não foi enviado com NF, não existe v...",0.939961,positive
41752,41752,99996.0,5.0,"Excelente mochila, entrega super rápida. Super...",0.984625,positive
41753,41753,99998.0,1.0,Solicitei a compra de uma capa de retrovisor c...,0.337860,negative
41754,41754,99999.0,1.0,"meu produto chegou e ja tenho que devolver, po...",0.240128,negative

In [7]:
df_semantic.columns
df_semantic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41755 entries, 0 to 41754
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              41755 non-null  int64
 1   indx                    41753 non-null  float64
 2   review_score            41755 non-null  float64
 3   review_comment_message  41753 non-null  object
 4   review_model_score      41751 non-null  float64
 5   polarity                41751 non-null  object
dtypes: float64(3), int64(1), object(2)
memory usage: 1.9+ MB

In [8]:
df_semantic.dropna(subset = ["review_comment_message"], inplace=True)

In [9]:
df_semantic["indx"] = df_semantic["indx"].astype(np.int64)
df_semantic[df_semantic["review_score"]==1.0]

,Unnamed: 0,indx,review_score,review_comment_message,review_model_score,polarity
6,6,19,1.0,Péssimo,0.354738,negative
11,11,29,1.0,Não gostei ! Comprei gato por lebre,0.990161,positive
12,12,32,1.0,Sempre compro pela Internet e a entrega ocorre...,0.404186,negative
17,17,39,1.0,Nada de chegar o meu pedido.,0.583349,neutral
22,22,51,1.0,recebi somente 1 controle Midea Split ESTILO.\...,0.212524,negative
...,...,...,...,...,...,...
41724,41724,99916,1.0,Ate hoje dia 21/10/2017 o pedido não foi entre...,0.247786,negative
41731,41731,99930,1.0,Eu recebi o seguinte email e preciso saber com...,0.823035,positive
41737,41737,99944,1.0,Boa tarde. \r\nNão recebo todos os produtos fa...,0.361992,negative
41753,41753,99998,1.0,Solicitei a compra de uma capa de retrovisor c...,0.337860,negative
41754,41754,99999,1.0,"meu produto chegou e ja tenho que devolver, po...",0.240128,negative

In [10]:
mergedDF=df_orders.merge(df_semantic, left_index=True, right_on='indx')
mergedDF[mergedDF["order_id"]=='e6ce16cb79ec1d90b1da9085a6118aeb']

,review_id,order_id,review_score_x,review_comment_title,review_comment_message_x,review_creation_date,review_answer_timestamp,Unnamed: 0,indx,review_score_y,review_comment_message_y,review_model_score,polarity
21018,15898b543726a832d4137fbef5d1d00e,e6ce16cb79ec1d90b1da9085a6118aeb,1,NaN,Aguardando retorno da loja,2017-05-30 00:00:00,2017-05-30 23:13:47,21018,50349,1.0,Aguardando retorno da loja,0.850365,positive

In [14]:
mergedDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41753 entries, 0 to 41754
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   review_id                 41753 non-null  object
 1   order_id                  41753 non-null  object
 2   review_score_x            41753 non-null  int64
 3   review_comment_title      9986 non-null   object
 4   review_comment_message_x  41753 non-null  object
 5   review_creation_date      41753 non-null  object
 6   review_answer_timestamp   41753 non-null  object
 7   indx                      41753 non-null  int64
 8   review_score_y            41753 non-null  float64
 9   review_comment_message_y  41753 non-null  object
 10  review_model_score        41751 non-null  float64
dtypes: float64(2), int64(2), object(7)
memory usage: 3.8+ MB

## Original merged data

In [11]:
df_all = pd.read_csv("data_merged.csv")
df_all

,order_id,customer_id,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_city,customer_state,customer_lat,...,seller_lat,seller_lng,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,sao paulo,SP,-23.576983,...,-23.680729,-46.444238,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,barreiras,BA,-12.177924,...,-19.807681,-43.980427,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,vianopolis,GO,-16.745150,...,-21.363502,-48.229601,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,sao goncalo do amarante,RN,-5.774190,...,-19.837682,-43.924053,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,santo andre,SP,-23.676370,...,-23.543395,-46.262086,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108101,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,praia grande,SP,-24.001500,...,-21.930548,-50.498348,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0
108102,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,nova vicosa,BA,-17.898358,...,-23.553642,-46.452661,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0
108103,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,japuiba,RJ,-22.562825,...,-20.940578,-45.827237,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
108104,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,japuiba,RJ,-22.562825,...,-20.940578,-45.827237,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
108105,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,lapa,PR,-25.764308,...,-20.496251,-47.418434,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0

In [13]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108106 entries, 0 to 108105
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       108106 non-null  object
 1   customer_id                    108106 non-null  object
 2   order_purchase_timestamp       108106 non-null  object
 3   order_approved_at              108106 non-null  object
 4   order_delivered_carrier_date   108106 non-null  object
 5   order_delivered_customer_date  108106 non-null  object
 6   order_estimated_delivery_date  108106 non-null  object
 7   customer_city                  108106 non-null  object
 8   customer_state                 108106 non-null  object
 9   customer_lat                   108106 non-null  float64
 10  customer_lng                   108106 non-null  float64
 11  order_item_id                  108106 non-null  int64
 12  product_id                     108106 non-null  object
 13  seller_id                      108106 non-null  object
 14  shipping_limit_date            108106 non-null  object
 15  price                          108106 non-null  float64
 16  freight_value                  108106 non-null  float64
 17  seller_city                    108106 non-null  object
 18  seller_state                   108106 non-null  object
 19  seller_lat                     108106 non-null  float64
 20  seller_lng                     108106 non-null  float64
 21  product_category_name          108106 non-null  object
 22  product_name_lenght            108106 non-null  float64
 23  product_description_lenght     108106 non-null  float64
 24  product_photos_qty             108106 non-null  float64
 25  product_weight_g               108106 non-null  float64
 26  product_length_cm              108106 non-null  float64
 27  product_height_cm              108106 non-null  float64
 28  product_width_cm               108106 non-null  float64
dtypes: float64(13), int64(1), object(15)
memory usage: 23.9+ MB

In [10]:
df_all.columns

Index(['order_id', 'customer_id', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_city', 'customer_state', 'customer_lat', 'customer_lng',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'seller_city', 'seller_state', 'seller_lat',
       'seller_lng', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [12]:
overall_df=df_all.merge(mergedDF, left_on='order_id', right_on='order_id')
overall_df

,order_id,customer_id,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_city,customer_state,customer_lat,...,review_comment_title,review_comment_message_x,review_creation_date,review_answer_timestamp,Unnamed: 0,indx,review_score_y,review_comment_message_y,review_model_score,polarity
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,sao paulo,SP,-23.576983,...,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,13883,33026,4.0,"Não testei o produto ainda, mas ele veio corre...",0.415931,negative
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,barreiras,BA,-12.177924,...,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,12366,29371,4.0,Muito bom o produto.,0.945978,positive
2,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,sao goncalo do amarante,RN,-5.774190,...,NaN,O produto foi exatamente o que eu esperava e e...,2017-12-03 00:00:00,2017-12-05 19:21:58,32694,78144,5.0,O produto foi exatamente o que eu esperava e e...,0.765808,positive
3,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00,rio de janeiro,RJ,-22.896463,...,NaN,Aguardando retorno da loja,2017-05-30 00:00:00,2017-05-30 23:13:47,21018,50349,1.0,Aguardando retorno da loja,0.850365,positive
4,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00,rio de janeiro,RJ,-22.896463,...,NaN,Aguardando retorno da loja,2017-05-30 00:00:00,2017-05-30 23:13:47,21018,50349,1.0,Aguardando retorno da loja,0.850365,positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46057,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,2017-12-20 09:52:41,2017-12-20 10:09:52,2017-12-20 20:25:25,2018-01-26 15:45:14,2018-01-18 00:00:00,campo do tenente,PR,-25.985590,...,NaN,"Ele não é um mini cajon, é um shaker, ou seja,...",2018-01-19 00:00:00,2018-01-21 02:51:39,6590,15702,1.0,"Ele não é um mini cajon, é um shaker, ou seja,...",0.073462,negative
46058,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,praia grande,SP,-24.001500,...,NaN,So uma peça que veio rachado mas tudo bem rs,2018-03-01 00:00:00,2018-03-02 17:50:01,23431,56100,4.0,So uma peça que veio rachado mas tudo bem rs,0.332948,negative
46059,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,nova vicosa,BA,-17.898358,...,NaN,Foi entregue antes do prazo.,2017-09-22 00:00:00,2017-09-22 23:10:57,18462,44186,5.0,Foi entregue antes do prazo.,0.889337,positive
46060,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,japuiba,RJ,-22.562825,...,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56,2881,6831,2.0,Foi entregue somente 1. Quero saber do outro p...,0.468871,neutral
46061,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,japuiba,RJ,-22.562825,...,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56,2881,6831,2.0,Foi entregue somente 1. Quero saber do outro p...,0.468871,neutral

In [14]:
overall_df.columns

Index(['order_id', 'customer_id', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_city', 'customer_state', 'customer_lat', 'customer_lng',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'seller_city', 'seller_state', 'seller_lat',
       'seller_lng', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'review_id', 'review_score_x', 'review_comment_title',
       'review_comment_message_x', 'review_creation_date',
       'review_answer_timestamp', 'Unnamed: 0', 'indx', 'review_score_y',
       'review_comment_message_y', 'review_model_score', 'polarity'],
      dtype='object')

In [16]:
overall_df[overall_df["order_id"]=='e6ce16cb79ec1d90b1da9085a6118aeb']

,order_id,customer_id,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_city,customer_state,customer_lat,...,review_comment_title,review_comment_message_x,review_creation_date,review_answer_timestamp,Unnamed: 0,indx,review_score_y,review_comment_message_y,review_model_score,polarity
3,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00,rio de janeiro,RJ,-22.896463,...,NaN,Aguardando retorno da loja,2017-05-30 00:00:00,2017-05-30 23:13:47,21018,50349,1.0,Aguardando retorno da loja,0.850365,positive
4,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00,rio de janeiro,RJ,-22.896463,...,NaN,Aguardando retorno da loja,2017-05-30 00:00:00,2017-05-30 23:13:47,21018,50349,1.0,Aguardando retorno da loja,0.850365,positive

In [17]:
overall_df.to_csv("full_data.csv")